Add lab roadmap-week05
LSE-DSI/lse-ds202-course-notes pull request #131
Opened 2022-10-07 16:52 UTC by UCLWilson

2022-10-08 14:46 UTC, jonjoncardoso commented
Closes #55 (once merged)

2022-10-08 14:50 UTC, jonjoncardoso requested changes
You pushed many files that should not be here.

Which IDE are you using? If VSCode, use the instructions I wrote on the README at this project [here](https://github.com/LSE-DSI/lse-ds202-course-notes#how-to-build-the-course-website).

Please delete all the html/css, etc files generated by Quarto and keep only the `.qmd`

2022-10-17 22:04 UTC, sbramwell86 commented on weeks/week05/lab.qmd
> +    ```
I think adding two different ways of coding the same function is confusion. Can we delete the first option? Generally when we create functions we use the curly brackets.

2022-10-17 22:09 UTC, sbramwell86 commented on weeks/week05/lab.qmd
> +	🏋️ There is a bonus for the senior students. You can explore the package `caret` for the LOOCV estimation.
I think it may not be the best idea to point to caret as the package is superceded by the tidymodels ecosystem.

2022-10-17 22:41 UTC, sbramwell86 commented on weeks/week05/lab.qmd
> +        K       1    -none- numeric
I think we can achieve the same thing by instantiating an empty vector to store results. We don't have to specify the length.

2022-10-17 23:12 UTC, sbramwell86 commented on weeks/week05/lab.qmd
> +	> y<-rnorm(3) #try to replicate the result from x again with the same seed
I really think that the root mean squared error is a better statistic.

2022-10-17 23:13 UTC, sbramwell86 commented on weeks/week05/lab.qmd
> +	```{r}
I have included rsample from the tidymodels ecosystem. It really simplifies things nicely, plus students have learned how to create train/test splits using base R in the last lesson.

2022-10-17 23:14 UTC, sbramwell86 commented on weeks/week05/lab.qmd
> +
So many students asked me how to create a graph like the one below so it seemed like a good time to add this.

2022-10-17 23:17 UTC, sbramwell86 commented on weeks/week05/lab.qmd
> +	> cv.err$delta
I would be wary of promoting caret as it has been superceded by tidymodels.

2022-10-18 11:30 UTC, sbramwell86 commented on weeks/week05/lab.qmd
> +
Can we delete Step 2? I think k-fold cross-validation and the bootstrap are more widely used resampling methods and the delta output for LOOCV is really confusing (what do the two values mean?). I don't think the website really adds much extra information to be honest. By contrast, if you specify K = 10, you get 10 MSEs which is more intuitive.

2022-10-19 10:41 UTC, jonjoncardoso requested changes

2022-10-19 10:41 UTC, jonjoncardoso commented on weeks/week05/lab.qmd
> +	```r
(I'm making the changes myself as I review it, but I will leave some comments here for future recommendations)

Make this an R cell instead of simple syntax highligthing. That is, replace \`\`\`r for ```{r}`

2022-10-19 10:41 UTC, jonjoncardoso commented on weeks/week05/lab.qmd
> +👉 [R for Data Analytics](https://rforanalytics.com/13.6-k-fold-cross-validation.html) (part of the courses by Abhay Singh)
(I'm making the changes myself as I review it, but I will leave some comments here for future recommendations)

Use bullet points instead of <br>

2022-10-19 10:41 UTC, jonjoncardoso commented on weeks/week05/lab.qmd
> +Please note, here we use new functions, namely `lm` and `predict`. By typing `?`, you can find the official explanation of these functions.
`lm` and `predict` are NOT NEW to students! They've been using it since W03

2022-10-19 10:41 UTC, jonjoncardoso commented on weeks/week05/lab.qmd
> +
I am of two minds about this. I think I will cover only k-fold CV and bootstrap in the lecture, but the Chapter 6 of the book provides an interesting discussion of the difference between LOOCV and k-fold CV, in light of bias vs variance tradeoff.

2022-10-19 10:41 UTC, jonjoncardoso commented on weeks/week05/lab.qmd
> +	```{r}
(I'm making the changes myself as I review it, but I will leave some comments here for future recommendations)

Make this an R cell instead of simple syntax highligthing. That is, replace ```r for ```{r}`

2022-10-19 10:41 UTC, jonjoncardoso commented on weeks/week05/lab.qmd
> +    boot.fn <- function(data, index) {
(I'm making the changes myself as I review it, but I will leave some comments here for future recommendations)

Make this an R cell instead of simple syntax highligthing. That is, replace ```r for ```{r}`

2022-10-19 10:41 UTC, jonjoncardoso commented on weeks/week05/lab.qmd
> +    ```r
(I'm making the changes myself as I review it, but I will leave some comments here for future recommendations)

Make this an R cell instead of simple syntax highligthing. That is, replace ```r for ```{r}`

2022-10-19 10:42 UTC, jonjoncardoso commented on weeks/week05/lab.qmd
> +
Good

2022-10-22 12:04 UTC, jonjoncardoso commented
Merged by c03455828ae08077d3fdacf60f728246e053d20c

2022-10-22 12:04 UTC, closed without merging